name: unit tests

env:
  CI: True

on: [push]

jobs:
  test-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn run test